version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongo_db_contanier_kube
    ports:
      - 27017:27017
    # restart: always
    volumes:
      - mongodockerkube:/data/configdb
      - mongodockerkube:/data/db

  api:
    build:
      context: .
    container_name: api_container_kube
    environment:
      NODE_ENV: production
    ports:
      - 6000:6000
    depends_on:
      - mongodb
    restart: always
    volumes:
      - .:/usr/src/app

volumes:
  mongodockerkube: {}
