version: "3.0"

# Services to run
services:
  mongo_db: # name of BD service
    image: mongo
    container_name: mongo_api_errors
    ports:
      - 27017:27017
    volumes:
      - apierros:/data/configdb
      - apierros:/data/db
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  apierros:
