const studentsData = [
  {
    firstName: "Steffen",
    lastName: "Terzo",
    age: 36,
    dni: "15691240",
    course: "Programación Backend",
    grade: 9,
    gender: "M",
  },
  {
    firstName: "Jorgan",
    lastName: "Matthis",
    age: 27,
    dni: "29358120",
    course: "Programación Frontend",
    grade: 6,
    gender: "M",
  },
  {
    firstName: "Haley",
    lastName: "Proback",
    age: 34,
    dni: "51241268",
    course: "Diseño UX/UI",
    grade: 7,
    gender: "M",
  },
  {
    firstName: "Michelina",
    lastName: "Beaglehole",
    age: 34,
    dni: "24614567",
    course: "Diseño UX/UI",
    grade: 6,
    gender: "F",
  },
  {
    firstName: "Jeralee",
    lastName: "Postans",
    age: 26,
    dni: "97212450",
    course: "Programación Frontend",
    grade: 6,
    gender: "F",
  },
  {
    firstName: "Jordain",
    lastName: "Kerner",
    age: 35,
    dni: "41262234",
    course: "Programación Backend",
    grade: 5,
    gender: "M",
  },
  {
    firstName: "Harriett",
    lastName: "Skeene",
    age: 33,
    dni: "21245129",
    course: "Programación Backend",
    grade: 10,
    gender: "F",
  },
  {
    firstName: "Andie",
    lastName: "McIlrath",
    age: 20,
    dni: "59127389",
    course: "Programación Frontend",
    grade: 9,
    gender: "M",
  },
  {
    firstName: "Sapphira",
    lastName: "Arnholtz",
    age: 17,
    dni: "03128893",
    course: "Programación Backend",
    grade: 5,
    gender: "F",
  },
  {
    firstName: "Terra",
    lastName: "Wadsworth",
    age: 31,
    dni: "02213850",
    course: "Diseño UX/UI",
    grade: 10,
    gender: "F",
  },
];

module.exports = studentsData;
