version: "3.0"

# Services to run
services:
  mongo_strategy: # name of BD service
    image: mongo
    container_name: mongo_db_practica_integradora_2
    ports:
      - 27017:27017
    volumes:
      - mpracticintegradora2:/data/configdb
      - mpracticintegradora2:/data/db
    # restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  mpracticintegradora2:
