version: "3.0"

# Services to run
services:
  mongo_db: # name of BD service
    image: mongo
    container_name: api_compress_p1
    ports:
      - 27017:27017
    volumes:
      - apicompress:/data/configdb
      - apicompress:/data/db
    # restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  apicompress:
